controllers:
    resource: ../src/Controller/
    type: attribute

# api/config/routes.yaml
auth:
    path: /auth
    methods: ['POST']

coop_tilleuls_forgot_password:
    resource: .
    type: coop_tilleuls_forgot_password
    prefix: '/forgot-password'
